---
{{- if .Values.backup.enable }}
{{- if not .Values.backup.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-backup
spec:
  storageClassName: {{ .Values.backup.storageClass }}
  accessModes:
    - {{ .Values.backup.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backup.size }}
{{- end }}
{{- end }}
